[window]
padding.x = 2
option_as_alt = "OnlyLeft"

[font]
size = 17
normal = { family = "Monaspace Neon", style = "Regular"}
italic = { family = "Monaspace Neon", style = "Italic"}
bold = { family = "Monaspace Neon", style = "Bold"}
bold_italic = { family = "Monaspace Neon", style = "Bold Italic"}

[scrolling]
history = 50000

# Kanagawa Dragon Alacritty Colors
# https://github.com/rebelot/kanagawa.nvim/blob/master/extras/alacritty/kanagawa_dragon.toml
[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black = '#0d0c0c'
red = '#c4746e'
green = '#8a9a7b'
yellow = '#c4b28a'
blue = '#8ba4b0'
magenta = '#a292a3'
cyan = '#8ea4a2'
white = '#c8c093'

[colors.bright]
black = '#a6a69c'
red = '#e46876'
green = '#87a987'
yellow = '#e6c384'
blue = '#7fb4ca'
magenta = '#938aa9'
cyan = '#7aa89f'
white = '#c5c9c5'

[colors.selection]
background = '#2d4f67'
foreground = '#c8c093'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#b98d7b'
